name: Rust

on:
  push:
    branches: [master, dev]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SKIP_WASM_BUILD: 1

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Install protoc (Protocol Buffers compiler)
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          export PROTOC=$(which protoc)
          
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: node

      - name: Build project and run integration tests
        run: |
          cargo build --manifest-path node/Cargo.toml --all-targets --all-features &&
          cargo test --manifest-path node/Cargo.toml -p pallet-perun --all-features